DROP TABLE IF EXISTS document_result;

CREATE TABLE document_result (
	id INT AUTO_INCREMENT PRIMARY KEY,
	task_Id VARCHAR(250) NOT NULL,
	result CLOB NOT NULL
);

DROP TABLE IF EXISTS task;

CREATE TABLE task ( 
	id INT AUTO_INCREMENT PRIMARY KEY,
	task_Id VARCHAR(250) NOT NULL,
	status VARCHAR(15) NOT NULL
);